columns:
  age: int
  gender: str
  polyuria: str
  polydipsia: str
  sudden_weight_loss: str
  weakness: str
  polyphagia: str
  genital_thrush: str
  visual_blurring: str
  itching: str
  irritability: str
  delayed_healing: str
  partial_paresis: str
  muscle_stiffness: str
  alopecia: str
  obesity: str
  class: str

categorical_columns:
  - Gender
  - Polyuria
  - Polydipsia
  - sudden weight loss
  - weakness
  - Polyphagia
  - Genital thrush
  - visual blurring
  - Itching
  - Irritability
  - delayed healing
  - partial paresis
  - muscle stiffness
  - Alopecia
  - Obesity
  - class

numerical_columns:
  - Age
